Checklist for java based SCR projects
!/bin/bash
s
grep -ir "//" *;
grep -ir "crypt" * ;
grep -ir "pass*" * ;
grep -ir "pass" * ;
grep -ir "file" * ;
grep -ir "getName" *; 
grep -ir "blowfish" *; 
grep -ir "cipher.getInstance" * ;
grep -ir "manager.getEngineByName" *; 
grep -ir "req.getParameter" * ;
grep -ir "request.getInputStream" * ;
grep -ir "out.write" * ;
grep -ir "initialize(1024)" * ;
grep -ir "keygen1.init(64)" * ;
grep -ir "sql" * ;
grep -ir "select" *; 
grep -ir "statement.executeQuery" * ;
grep -ir "ejb-interceptors.xml" * ;
grep -ir "Entity" * ;
grep -ir "/etc/shadow" * ;
grep -ir "database.password" * ;
grep -ir "DriveManager.getConnection" * ;
grep -ir "fileutils.forcedelete" * ;
grep -ir "ldap" *;
grep -ir "userPassword" * ;
grep -ir "runtime.getruntime().exec" * ;
grep -ir "request.getParameter" * ;
grep -ir "Footest" * ;
grep -ir "session" * ;
grep -ir "secure flag" * ;
grep -ir "secure.cookie" * ;
grep -ir "httponly" * ;
grep -ir "session.fixation" * ;
grep -ir "key" * ;
grep -ir "io.jsonwebtoken.jwts.builder" *;
grep -ir "cipher.getinstance("des")" * ;
grep -ir "cipher.getinstance("desedw")" * ;
grep -ir "cipher.getinstance("desede")" * ;
grep -ir "cipher.getinstance("RC2")" * ;
grep -ir "cipher.getinstance("RC2") * ;
grep -ir "cipher.getinstance("RC2")" * ;
grep -ir "cipher.getinstance("RC4")" * ;
grep -ir "cipher.getinstance("blowfish")" * ;
grep -ir "sethostnameverifier" * ;
grep -ir "urlconnection.sethostnameverifier" * ;
grep -ir "mkdir" * ;
grep -ir "resp.addheader("X-Header")" * ;
grep -ir "X509Certificate" * ;
grep -ir "antmatchers" * ;
grep -ir "byte[] salt" * ;
grep -ir "salt" * ;
grep -ir "url = new url(req.getparameter)" * ;
grep -ir "httpurlconnection conn = (HttpURLConnection) url2.openConnection()" * ;
grep -ir "whitelisted" * ;
grep -ir "sslv3" * ;
grep -ir "sslcontext.getInstance" * ;
grep -ir "InetAddress addr = InetAddress.getbyname" * ;
grep -ir "x-powered-by" * ;
grep -ir "access-control-allow-origin" * ;
grep -ir "builder.command" * ;
grep -ir "email.setsmtpPort" * ;
grep -ir "email.setSSLOnConnect" * ;
grep -ir "XML" * ;
grep -ir "executeQuery" * ;
grep -ir "transformerfactory.newinstance" * ;
grep -ir "SHA-1" * ;
grep -ir "stacktrace" * ;
grep -ir "e.printstacktrace" *;